backend:
  name: github
  repo: demetrisva/geoconsultants
  branch: main
  base_url: https://cms-auth.geoconsultants.eu   # your Worker domain
  auth_endpoint: /auth

site_url: https://www.geoconsultants.eu
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
logo_url: /assets/logo.svg

# Simple = edit → commit straight to main (no PRs)
publish_mode: simple

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home (index.html)"
        name: "home"
        file: "index.html"
        editor: { preview: false }
        fields:
          - { label: "HTML", name: "raw", widget: "code", allow_language: "html" }

      - label: "About"
        name: "about"
        file: "about/index.html"
        editor: { preview: false }
        fields:
          - { label: "HTML", name: "raw", widget: "code", allow_language: "html" }

      - label: "Services"
        name: "services"
        file: "services/index.html"
        editor: { preview: false }
        fields:
          - { label: "HTML", name: "raw", widget: "code", allow_language: "html" }

      - label: "Contact"
        name: "contact"
        file: "contact/index.html"
        editor: { preview: false }
        fields:
          - { label: "HTML", name: "raw", widget: "code", allow_language: "html" }
